package xiaozhi.common.utils;

import static org.junit.jupiter.api.Assertions.assertEquals;

import org.junit.jupiter.api.Test;

class SM2FrontendCompatibilityTest {

    /**
     * Ciphertext generated by manager-web-next with sm-crypto 0.5.5 in
     * C1C3C2 mode. This protects the wire-format contract used by login,
     * registration, and password recovery.
     */
    @Test
    void decryptsFrontendC1C3C2Ciphertext() {
        String privateKey = "7d439ec33c0e6597348f1d4ab6e426166d93eb008104147168b380dcbe536c93";
        String ciphertext = "04c061e1caa017e89dbe727f84eaabdf8bd512d007866577e637eec46ea529e689c1602b00efcc9175198face73b290b9c32eba8fd0c851d9a3f08800029a2b1eaf1a40ef538fc54f30ea070f78c9fae8908bd8cddb0bc6ff7115c1378922b2875297a237e6f72ca6c8ad241e072097c5b5de3";

        assertEquals("a1b2cTestPassword!", SM2Utils.decrypt(privateKey, ciphertext));
    }
}
